### ISSUE TITLE
PE32 analysis causes a infinite loop in the main thread, unless the database had older version of classinformer used on it before. (RC1)

### ISSUE THREAD

**Issue by eepycats** [EngineLessCC/ClassInformer-IDA-82-83-84#2]
I think the title describes the issue well, it seems to be getting stuck around here: https://github.com/enginelesscc/classinformer-ida-90/blob/216f4a0ac9098e547b41139d136ca43e11f73eb7/classinformer-code-r4/Plugin/Main.cpp#L534-L543
It'll be a few hrs until i can build this myself in debug with pdb and see exactly what it's dying at, might edit the issue later.

**Comment by enginelesscc** [comment]
Thanks!

Besides finding put that I have to update the initterm patterns for the new runtime, I was able to repro it on an older pe32 binary.

I'll take a look later.

**Comment by fishywitch** [comment]
It seems like is64bit == true (getPtrSize returns 8, create_qword is called)

**Comment by enginelesscc** [comment]
Correct

IDA defaults to 64bit ea and the plugin loads before the program is analyzed.
=> Classinformer thought the process is 64bit

I've moved the detection to run() and added a sanity check inside that ea loop just incase.

**Comment by fishywitch** [comment]
made is64bit (forcefully) false, and got a crash in get_size on this line
 https://github.com/enginelesscc/classinformer-ida-90/blob/216f4a0ac9098e547b41139d136ca43e11f73eb7/classinformer-code-r4/Plugin/RTTI.cpp#L195

i guess thats also related to the 64bit ea default

**Comment by enginelesscc** [comment]
Already solved, please test the new release

**Comment by fishywitch** [comment]
yup, that works, tysm <3
